name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Get OpenAPI files
      run:  |
        # Using github env (newline separated file list)
        echo 'FILE_LIST<<EOF' >> $GITHUB_ENV
        find lib -type f -iname "*openapi.yaml" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

        # Using step output (space separated file list)
        FILES="$(find lib -type f -iname "*openapi.yaml")"
        echo "::set-output name=file_list::$FILES"
    - name: swagger-validator
      uses: mbowman100/swagger-validator-action@master
      if: env.FILE_COUNT != '0' # Comment out if you want it to fail if no files found
      with:
        files: ${{ env.FILE_LIST }}
        # files: ${{ steps.getfiles.outputs.file_list }} # For if you're using output
